#!/bin/bash -x

curl -v http://localhost:8082/echo/once?text=1 
ab -k -n 1000 -c 1000 http://localhost:8082/echo/once?text=1 

curl -v http://localhost:8082/echo/oncec?text=1 
ab -k -n 1000 -c 1000 http://localhost:8082/echo/oncec?text=1

curl -v http://localhost:8082/echo/onced?text=1
ab -k -n 1000 -c 1000 http://localhost:8082/echo/onced?text=1

curl -v http://localhost:8082/echo/oncer?text=1
ab -k -n 1000 -c 1000 http://localhost:8082/echo/oncer?text=1
